backend:
  name: git-gateway
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "src/content/articulos"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "string" }

      - label: "Categoría"
        name: "categoria"
        widget: "select"
        options:
          - { label: "Política", value: "politica" }
          - { label: "Sociedad", value: "sociedad" }
          - { label: "Economía", value: "economia" }
          - { label: "Cultura", value: "cultura" }
          - { label: "Opinión", value: "opinion" }

      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Imagen de portada", name: "cover", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }